floo/account/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import *

app_name = 'account'

urlpatterns=[
    path('register/', register_view, name="register"),
    path('login/',login_view,name="login"),
    path('logout/', logout_view, name="logout"),

]

floo/community/urls.py
from django.contrib import admin
# from accounts import views
from community import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name ="community"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('bill_main/', views.bill_main, name="bill_main"),
    path('bill/<str:bill_id>', views.bill_detail, name="bill_detail"),
    path('bill_write/', views.bill_write, name="bill_write"),
    path('bill_create/', views.bill_create, name="bill_create"),
    path('bill_delete/<str:bill_id>', views.bill_delete, name="bill_delete"),
    path('debate/<str:debate_id>', views.debate_detail, name="debate_detail"),
    path('debate_main/', views.debate_main, name="debate_main"),
    path('mypage/',views.mypage,name="mypage"),
    path('bill/<str:bill_id>/comment/', views.comment_to_bill, name="comment_to_bill"),
    path('debate/<str:debate_id>/comment/', views.comment_to_debate, name="comment_to_debate"),
    path('forbidden/',views.forbidden,name="forbidden"),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/floo/urls.py
from django.contrib import admin
from account import views
from main import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('', views.main, name='main'),  
    path('FLOO/', include('community.urls')),
    path('mbti/', include('mbti.urls')),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/mbti/urls.py
from django.contrib import admin
# from accounts import views
from mbti import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mbti'

urlpatterns = [
    path('main/', views.test_main, name='test_main'),
    path('mbti1/', views.mbti1, name="mbti1"),
    path('mbti2/', views.mbti2, name="mbti2"),
    path('mbti3/', views.mbti3, name="mbti3"),
    path('mbti4/', views.mbti4, name="mbti4"),
    path('mbti5', views.mbti5, name="mbti5"),
    path('mbti6/', views.mbti6, name="mbti6"),
    path('mbti7/', views.mbti7, name="mbti7"),
    path('mbti8/', views.mbti8, name="mbti8"),
    path('mbti9/', views.mbti9, name="mbti9"),
    
    path('mbti10/', views.mbti10, name="mbti10"),
    path('result/', views.result, name="result"),







] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/floo/templates/shared/footer.html
<footer class="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h5>About Us</h5>
                        <p>We Floo Team this word Fire and Yolo combinations We developed this site for yolo&fire people</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h4 style="color: aliceblue;"> Social</h4>
                        <div>
                            <p>
                            <a href="https://www.twitter.com" class="fa-icon" title="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                                <a href="https://www.facebook.com" class="fa-icon" title="">
                                    <i class="fa fa-facebook" aria-hidden="true"></i>
                                </a>
                                <a href="https://www.linkedin.com" class="fa-icon" title="">
                                    <i class="fa fa-instagram" aria-hidden="true"></i>
                                </a>
                            </p>
                        </div>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h5>Version</h5>
                        <p>1.0</p>
                    </div>
                </div>
            </div>
        </div>
    </footer><!-- footer -->

floo/floo/templates/shared/navbar.html
    <header id="header" style="background-color: #CCDBE2;"> 
        <div class="header-content clearfix primary-nav" >
            <a class="logo" href="#">FLOO</a>
            <nav class="navigation" role="navigation">
                <ul class="primary-nav">
                    <li><a href="{% url 'community:bill_main' %}">영수증</a></li>
                    <li><a href="{% url 'mbti:test_main' %}">MBTI 테스트</a></li>
                    <li><a href="{% url 'community:debate_main' %}">토론</a></li>
                    {%if user.is_authenticated%}
                    <li class="nav-item"><a href="{% url 'community:mypage'%}" class="nav-link">마이페이지</a></li>
                    <li class="nav-item cta"><a href="{%url 'account:logout'%}" class="nav-link">로그아웃</a></li>
                    <!-- <li class="nav-item"><a href="{%url 'account:login'%}" class="nav-link">로그아웃</a></li> -->
                    {% else %}
                    <li class="nav-item cta"><a href="{%url 'account:login'%}" class="nav-link">로그인</a></li>
                    <li class="nav-item cta"><a href="{%url 'account:register'%}" class="nav-link">회원가입</a></li>
                    {% endif %}

                </ul>
            </nav>
            <a href="#" class="nav-toggle">Menu<span></span></a>
        </div>
    </header>

floo/floo/templates/shared/navber.html
<section class="banner" role="banner">
    <header id="header">
        <div class="header-content clearfix">
            <!-- <a class="logo" href="#"><img src="images/logo.png" alt=""></a> -->
            <a class="logo" href="#">FLOO</a>
            <nav class="navigation" role="navigation">
                <ul class="primary-nav">
                    <li><a href="#features">Features</a></li>
                    <li><a href="#works">Works</a></li>
                    <li><a href="#teams">Our Team</a></li>
                    <li><a href="#testimonials">Testimonials</a></li>
                    <li><a href="#download">Download</a></li>
                </ul>
            </nav>
            <a href="#" class="nav-toggle">Menu<span></span></a>
        </div><!-- header content -->
    </header><!-- header -->
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="banner-text text-center">
                <h1>Your Favorite One Page Multi Purpose Template</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna vel scelerisque nisl consectetur et.</p>
                <a href="#" class="btn btn-large">Find out more</a>
            </div><!-- banner text -->
        </div>
    </div>
</section>