floo/community/urls.py
from django.contrib import admin
# from accounts import views
from community import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name ="community"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('bill_main/', views.bill_main, name="bill_main"),
    path('bill/<str:bill_id>', views.bill_detail, name="bill_detail"),
    path('bill_write/', views.bill_write, name="bill_write"),
    path('bill_create/', views.bill_create, name="bill_create"),
    path('bill_delete/<str:bill_id>', views.bill_delete, name="bill_delete"),
    path('debate/<str:debate_id>', views.debate_detail, name="debate_detail"),
    path('debate_main/', views.debate_main, name="debate_main"),
    path('mypage/',views.mypage,name="mypage"),
    path('bill/<str:bill_id>/comment/', views.comment_to_bill, name="comment_to_bill"),
    path('debate/<str:debate_id>/comment/', views.comment_to_debate, name="comment_to_debate"),
    path('forbidden/',views.forbidden,name="forbidden"),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/floo/urls.py
from django.contrib import admin
from account import views
from main import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('', views.main, name='main'),  
    path('FLOO/', include('community.urls')),
    path('mbti/', include('mbti.urls')),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/mbti/urls.py
from django.contrib import admin
# from accounts import views
from mbti import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mbti'

urlpatterns = [
    path('main/', views.test_main, name='test_main'),
    path('mbti1/', views.mbti1, name="mbti1"),
    path('mbti2/', views.mbti2, name="mbti2"),
    path('mbti3/', views.mbti3, name="mbti3"),
    path('mbti4/', views.mbti4, name="mbti4"),
    path('mbti5', views.mbti5, name="mbti5"),
    path('mbti6/', views.mbti6, name="mbti6"),
    path('mbti7/', views.mbti7, name="mbti7"),
    path('mbti8/', views.mbti8, name="mbti8"),
    path('mbti9/', views.mbti9, name="mbti9"),
    
    path('mbti10/', views.mbti10, name="mbti10"),
    path('result/', views.result, name="result"),







] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/main/models.py
from django.db import models

# Create your models here.

floo/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.db import models


# Create your views here.
def main(request):
    
    return render(request, 'main.html')

floo/main/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FLOO</title>
</head>
<style>
    html { box-sizing: border-box; } *, *::before, *::after { box-sizing: inherit; }
html {
  height: 100vh;
  font-size: 10px;
}
body {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(to right, #bcd6d7, rgb(193, 193, 195));
  color: #fff;
  font-family: "Lato", sans-serif;
  font-size: 4rem;
  font-weight: 300;
  

  ins {
    color: greenyellow;
    cursor: pointer;
    border: 2px solid greenyellow;
    padding: 2px 12px 2px 12px;
    border-radius: 28px;
    text-decoration: none;
    
    &::before {
      font-size: 0;
      content: '+ ';
      &:hover {
        animation: typing 4s;
        animation-fill-mode: forwards;
      }
    }
    
    &:focus {
      outline: none;
      
      &::before {
        animation: typing 4s;
        animation-fill-mode: forwards;
      }
      
      &+del {
        animation: before-setup 4s;
        animation-fill-mode: forwards;
        
        &::before {
          animation: typing 4s;
          animation-fill-mode: forwards;
        }
      }
    }
  }
}

@keyframes typing {
  0% { font-size: 0; }
  100% { font-size: 4rem;}
}

@keyframes before-setup {
  0% { 
    font-size: 0;
    border: 2px solid darkred;
    padding: 2px 12px 2px 12px;
    border-radius: 28px;
  }
  100% { 
    font-size: 4rem;
    border: 2px solid darkred;
    padding: 2px 12px 2px 12px;
    border-radius: 28px;
  }
}
button{
    border-radius: 10px;
    border: 1px black;
}

.tile{
  display: inline;
  height: 100px;
  text-align: center;
  justify-content: center;
  margin: 30px;

  padding: 20px;
}

button{
  border: none;
  padding: 15px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  margin-top: 20px;
  cursor: pointer;
  font-weight: 500;
}
</style>
<body>
    



    <main style="height: -120px;">
        <p>
            <ins tabindex="0">FLOO</ins>에 오신것을 환영합니다.
          </p>
          <div class="tile" >
            <a href="{% url 'community:home' %}"><button>Home</button></a>
        </div>
          
        <div class="tile" >
          <a href="{% url 'mbti:test_main' %}"><button>MBTI TEST</button></a>
      </div>
    </main>
    
    

    
    
</body>
</html>