floo/account/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import *

app_name = 'account'

urlpatterns=[
    path('register/', register_view, name="register"),
    path('login/',login_view,name="login"),
    path('logout/', logout_view, name="logout"),

]

floo/floo/urls.py
from django.contrib import admin
from account import views
from main import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('', views.main, name='main'),  
    path('FLOO/', include('community.urls')),
    path('mbti/', include('mbti.urls')),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/mbti/urls.py
from django.contrib import admin
# from accounts import views
from mbti import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mbti'

urlpatterns = [
    path('main/', views.test_main, name='test_main'),
    path('mbti1/', views.mbti1, name="mbti1"),
    path('mbti2/', views.mbti2, name="mbti2"),
    path('mbti3/', views.mbti3, name="mbti3"),
    path('mbti4/', views.mbti4, name="mbti4"),
    path('mbti5', views.mbti5, name="mbti5"),
    path('mbti6/', views.mbti6, name="mbti6"),
    path('mbti7/', views.mbti7, name="mbti7"),
    path('mbti8/', views.mbti8, name="mbti8"),
    path('mbti9/', views.mbti9, name="mbti9"),
    
    path('mbti10/', views.mbti10, name="mbti10"),
    path('result/', views.result, name="result"),







] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/mbti/models.py
from django.db.models.deletion import CASCADE
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser






User = get_user_model()


class Mbti_count(models.Model):
    count_num = models.IntegerField(default=0, blank=True, null=True)

floo/mbti/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.db import models
from .models import Mbti_count

# Create your views here.

count_num = 0
participation = 0



def test_main(request): #test mainpage
    return render(request, "test_main.html")
def mbti1(request):  # 1 로 이동

    return render(request, 'mbti1.html',  {'count_num' : count_num})


def mbti2(request):  # 2로 이동

    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti2.html',  {'count_num' : count_num})


def mbti3(request):  # 3로 이동
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti3.html',  {'count_num' : count_num})


def mbti4(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti4.html')


def mbti5(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti5.html')


def mbti6(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti6.html')


def mbti7(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti7.html')


def mbti8(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)

    return render(request, 'mbti8.html')


def mbti9(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
    return render(request, 'mbti9.html')


def mbti10(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)

    return render(request, 'mbti10.html')


def result(request):
    global count_num
    if(request.method == 'POST'):
        count_n = request.POST['answer']
        count_num += int(count_n)
        user = Mbti_count()
        if(count_num>100):
            count_num-=100
        if(count_num<-100):
            count_num+=100    
        user.count_num = count_num

    return render(request, 'result.html', {'count_num' : count_num})

floo/mbti/templates/mbti1.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            
            <h3>로또 1등 당첨되면?</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti2' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>일단 쓴다</button>
                        <button type="submit" name="answer" value=10>저축한다</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>


</html>

floo/mbti/templates/mbti10.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>일을 할때,</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:result' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>쉬는 것도 중요!<br>
                                                                      주말에는 쉬자</button>
                        <button type="submit" name="answer" value=10>돈버는게 최고<br>
                                                                    주말도 일하자</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti2.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            
            <h3>새로운 취미가 생겼다.</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div >
                    <form action="{% url 'mbti:mbti3' %}" method="POST" enctype=multipart/form-data>
                        
                            {%csrf_token%}
                    <div class="qna">
                        <button type="submit" name="answer" value=-10>일단 장비부터<br>구매한다</button>
                        <button type="submit" name="answer" value=10>일단 장비를 빌려서<br>시작한다</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti3.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
           
            <h3>택시를 자주 타는 편?</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti4' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>O</button>
                        <button type="submit" name="answer" value=10>X</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti4.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>전셋집 인테리어를</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti5' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>한다</button>
                        <button type="submit" name="answer" value=10>안한다</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti5.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>너무 피곤한 당신.. 커피를</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti6' %}" method="POST" enctype=multipart/form-data>{% csrf_token %}
                    <div>
                        
                        <button type="submit" name="answer" value=-10>사먹는다</button>
                        <button type="submit" name="answer" value=10>타먹는다</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti6.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>돈은 쓰기 위해 버는 것이다</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti7' %}" method="POST" enctype=multipart/form-data>{%csrf_token%}
                        <div>
                        
                        <button type="submit" name="answer" value=-10>O</button>
                        <button type="submit" name="answer" value=10>X</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti7.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>둘중에 만약 선물을 받게 된다면?</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti8' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>슈퍼카</button>
                        <button type="submit" name="answer" value=10>원룸</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti8.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>주식이 10% 올랐을 때,</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                    <form action="{% url 'mbti:mbti9' %}" method="POST" enctype=multipart/form-data>
                        <div>
                            {%csrf_token%}
                        <button type="submit" name="answer" value=-10>바로 판다</button>
                        <button type="submit" name="answer" value=10>존버한다</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/mbti9.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI_TEST
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>사고싶은 옷을 발견했을 때,</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                <div class="qna">
                <form action="{% url 'mbti:mbti10' %}" method="POST" enctype=multipart/form-data>
                    <div>
                        {%csrf_token%}
                        <button type="submit" name="answer" value=-10>지금 당장 사야해!</button>
                        <button type="submit" name="answer" value=10>좀 돌아보고 오자</button>
                    </div>
                </form>
                </div>
            </p>
        </section>
        </div>
    </body>

</html>

floo/mbti/templates/test_main.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            MBTI testimonial-2
        </title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
    
        <link rel = "stylesheet" href="{% static 'css/default.css' %}">
        <link rel = "stylesheet" href="{% static 'css/mbti_main.css' %}">
        <link rel = "stylesheet" href="{% static 'css/qna.css' %}">
    </head>

    <body>
        
        <div class="container-fluid" >
        <section class = "mx-auto mt-5 pt-5 pb-5 px-3" id="mbti_main" >
            <h3>당신의 소비성향은?</h3>
            <div class="col-6 pt-5 pb-5 mx-auto" >
                <img class="img-fluid" src="{% static 'image/fire.png'%}" alt="main page image"
                style="max-width:10%; height:auto;">
            </div>
            <p>
                FIRE OR YOLO<br>
                당신은 어느 쪽일까요?<br>
            </p>
            <a href="{% url 'mbti:mbti1' %}"><button type="button" class="btn btn-outline-danger mt-5">mbti시작하기</button></a><br>
            
        </section>
        <script src="{% static 'js/start.js'%}" charset="utf-8"></script>
        </div>
    </body>

</html>