floo/community/urls.py
from django.contrib import admin
# from accounts import views
from community import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name ="community"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('bill_main/', views.bill_main, name="bill_main"),
    path('bill/<str:bill_id>', views.bill_detail, name="bill_detail"),
    path('bill_write/', views.bill_write, name="bill_write"),
    path('bill_create/', views.bill_create, name="bill_create"),
    path('bill_delete/<str:bill_id>', views.bill_delete, name="bill_delete"),
    path('debate/<str:debate_id>', views.debate_detail, name="debate_detail"),
    path('debate_main/', views.debate_main, name="debate_main"),
    path('mypage/',views.mypage,name="mypage"),
    path('bill/<str:bill_id>/comment/', views.comment_to_bill, name="comment_to_bill"),
    path('debate/<str:debate_id>/comment/', views.comment_to_debate, name="comment_to_debate"),
    path('forbidden/',views.forbidden,name="forbidden"),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/floo/urls.py
from django.contrib import admin
from account import views
from main import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('', views.main, name='main'),  
    path('FLOO/', include('community.urls')),
    path('mbti/', include('mbti.urls')),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/mbti/urls.py
from django.contrib import admin
# from accounts import views
from mbti import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mbti'

urlpatterns = [
    path('main/', views.test_main, name='test_main'),
    path('mbti1/', views.mbti1, name="mbti1"),
    path('mbti2/', views.mbti2, name="mbti2"),
    path('mbti3/', views.mbti3, name="mbti3"),
    path('mbti4/', views.mbti4, name="mbti4"),
    path('mbti5', views.mbti5, name="mbti5"),
    path('mbti6/', views.mbti6, name="mbti6"),
    path('mbti7/', views.mbti7, name="mbti7"),
    path('mbti8/', views.mbti8, name="mbti8"),
    path('mbti9/', views.mbti9, name="mbti9"),
    
    path('mbti10/', views.mbti10, name="mbti10"),
    path('result/', views.result, name="result"),







] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floo/community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Bill(models.Model):
    image= models.ImageField(null=False)
    date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) 
    text=models.CharField(max_length=200)
    title=models.CharField(max_length=30)
    yolo=models.IntegerField(default=0)
    fire=models.IntegerField(default=0)

    def summary(self):
        return self.text[:50]

class BillComment(models.Model):
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    text=models.CharField(max_length=150)


    

class Debate(models.Model):
    text=models.CharField(max_length=200)
    title=models.CharField(max_length=100)

class DebateComment(models.Model):
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    text=models.CharField(max_length=150)
    like=models.IntegerField(default=0)
    debate = models.ForeignKey(Debate, on_delete=models.CASCADE)

floo/main/models.py
from django.db import models

# Create your models here.

floo/community/views.py
from django.shortcuts import get_object_or_404, render, redirect
from account.models import CustomUser
from .models import Bill, Debate, BillComment, DebateComment
from account.forms import RegisterForm
from django.db import models
from django.conf import settings
from django.utils import timezone


def home(request):
    return render(request,'home.html')

def bill_main(request):
    bills = Bill.objects.all()
    return render(request,'bill_main.html',{'bills':bills})

def bill_detail(request,bill_id):
    selected_bill = get_object_or_404(Bill, pk=bill_id)
    bill_comments=BillComment.objects.filter(bill=selected_bill)
    return render(request,'bill_detail.html',{'bill':selected_bill,'bill_comments':bill_comments})

def bill_write(request):
    return render(request,"bill_write.html")

def bill_create(request):
    if request.user.is_authenticated:
        new_bill=Bill()
        if 'image' in request.FILES:
            new_bill.image=request.FILES['image']
        new_bill.author=request.user
        new_bill.text=request.POST.get('bill_text',False)
        new_bill.title=request.POST.get('bill_title',False)
        new_bill.yolo=0
        new_bill.fire=0
        new_bill.save()
        return redirect('community:bill_detail', new_bill.id)
    else:
        return redirect('community:forbidden')

def bill_delete(request,bill_id):
    delete_bill = Bill.objects.get(id=bill_id)
    if delete_bill.author == request.user:
        delete_bill.delete()
        return redirect('community:bill_main')
    else:
        return redirect('community:forbidden')

def debate_detail(request,debate_id):
    selected_debate = get_object_or_404(Debate, pk=debate_id)
    debate_comments=DebateComment.objects.filter(debate=selected_debate)
    return render(request,"debate_detail.html",{'debate':selected_debate,'debate_comments':debate_comments})

def debate_main(request):
    debates=Debate.objects.all()
    return render(request, 'debate_main.html',{'debates':debates})

def mypage(request):
    myquest = request.POST.get('myquest')
    mybills = Bill.objects.filter(author=request.user)
    mydebates = DebateComment.objects.filter(author=request.user)
    return render(request,"mypage.html",{'bills':mybills,'debates':mydebates})


def comment_to_bill(request, bill_id):
    comment=BillComment()
    comment.author=request.user
    comment.text=request.POST.get('bill_comment_text',False)
    comment.bill=get_object_or_404(Bill, pk=bill_id)
    comment.save()
    return redirect('community:bill_detail',bill_id)


def comment_to_debate(request, debate_id):
    comment=DebateComment()
    comment.author=request.user
    comment.debate=get_object_or_404(Debate, pk=debate_id)
    comment.text=request.POST.get('debate_comment_text',False)
    comment.save()
    return redirect('community:debate_detail',debate_id)



def forbidden(request):
    return render(request,"forbidden.html")

floo/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.db import models


# Create your views here.
def main(request):
    
    return render(request, 'main.html')

floo/community/templates/404page.html
404page

floo/community/templates/bill_detail.html
{%extends 'base.html' %}
{%load static%}
{%block content%}

<link rel="stylesheet" href='{% static "bill_detail.css" %}' />
    <section style="margin: 200px 100px 100px 200px;">
        <div class="main-container">
            <div class="bill-info">
                {{bill.author}}
                {{bill.date}}
            </div>
            {% if bill.image %}
                <img src="{{bill.image.url}}" class="card-img-top" alt="...">
            {% endif %}

            <div class="right-section">
                {{bill.text}}
    
                <div class="buttons">
                    {%if user.is_authenticated %}
                        {%if user.username == bill.author.username %}
                            <a href="{%url 'community:bill_delete' bill.id %}" class="btn btn-light" >삭제하기</a>
                        {%endif%}
                    {%endif%}
                    
                    <br><br>
                    <a href="{%url 'community:bill_main'%}" class="btn btn-light" style="margin-bottom: 10%; font-family: 'ELAND_Choice_L'">목록으로 돌아가기</a>
                </div>
            </div>

        </div>
        
<!--
        <div class="comments" >
            <div class="allComments">
                <div class="container justify-content-center mt-5 border-left border-right">
                    <div class="d-flex justify-content-center pt-3 pb-2"> 
                        <form action="{% url 'community:comment_to_bill' bill.id %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="bill_comment_text" placeholder="+ 댓글을 달아보세요!" class="form-control addtxt" style="margin:0 auto; width:80%"/>
                        <button>추가</button>
                        {% for comment in bill_comments %}
                            <div class="d-flex justify-content-center py-2">
                                <div class="second py-2 px-2"> <span class="text1">{{comment.text}}</span></div>
                                <span class="thumbup"><i class="fa fa-thumbs-o-up"></i></span>
                            </div>
                            {{comment.author}}
                            {{comment.date}}
                        {% endfor %}
                        </form>
                </div>
            </div>
        </div>
    -->

        <div class="comments">
            <form action="{% url 'community:comment_to_bill' bill.id %}" method="POST">
                {% csrf_token %}
                <input type="text" name="bill_comment_text" placeholder="+ 댓글을 달아보세요!" class="form-control addtxt" style="margin:0 auto; width:80%"/>
                <input type="submit" style="border-radius: 5px; background:#88b2f1; border:none ;" value="Send"></input>
            </form>
                <div class="container mt-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8">
                        {% for comment in bill_comments %}
                        <div class="card p-3 mt-2">
                            <div class="d-flex justify-content-between align-items-center" style="margin:0 auto; width:80%">
                                <div class="user d-flex flex-row align-items-center"> 
                                    <span>
                                        <small class="font-weight-bold text-primary">{{comment.author}}</small> 
                                        <small class="font-weight-bold">{{comment.text}}</small>
                                    </span>
                                </div> 
                                <small>{{comment.date}}</small>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

floo/community/templates/bill_main.html
{%extends 'base.html' %}
{%load static%}
{%block content%}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>

<section style="margin: 100px 170px 100px 170px;">
<div class="row row-cols-1 row-cols-md-4 g-4" id="main-container">
    {% for bill in bills.all %}
    <a href="{%url 'community:bill_detail' bill.id %}" style="text-decoration-line: none;">
        <div class="col">
        <div class="card h-100" id="card" style="height: 100px;">
            {% if bill.image %}
                <img src="{{bill.image.url}}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h4 style="font-family: 'ELAND_Choice_L';">{{bill.title}}</h4>
                <small style="color:black; font-family: 'ELAND_Choice_L';">{{bill.summary}}</small>
            </div>
            <div class="card-footer" style="border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;">
            <small class="text-muted">
                <strong>{{bill.author}}</strong>
                {{bill.date}}
            </small>
            </div>
        </div>
        </div>
    </a>
    {% endfor %}
</div>
  
{%if user.is_authenticated %}
    <br><br><a href="{%url 'community:bill_write' %}" class="btn btn-light" style="font-family: 'Jeju Gothic', sans-serif;" >글쓰기</a><br><br>
{%else%}
    <br><br><div class="alert alert-secondary" style="font-family: 'Jeju Gothic', sans-serif;" role="alert">
    글을 쓰려면 로그인 해주세요!
</div>
{%endif%}
</section>

{%endblock%}
    

floo/community/templates/bill_write.html
영수증 폼 작성페이지입니다.

<form action="{%url 'community:bill_create' %}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    <textarea name="bill_text"></textarea>
    <textarea name="bill_title"></textarea>
    <button>추가</button>



    
</form>

floo/community/templates/debate_detail.html
{%extends 'base.html' %}
{%load static%}
{%block content%}

<style>


@font-face {
    font-family: 'ELAND_Nice_M';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/ELAND_Nice_M.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'ELAND_Choice_M';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/ELAND_Choice_M.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'SBAggroB';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/SBAggroB.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Pretendard-Regular';
    src: url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff') format('woff');
    font-weight: 400;
    font-style: normal;
}
    body {
  background-color: #FCF6F5;
  display:flex;
  flex-flow:row wrap;
  justify-content:center;
  margin:0;
  height:100vh;
  align-items:center;
  align-content:center;
  padding:0 8rem;
}

.ma {
    font-family: 'ELAND_Nice_M';
    text-align: center;
    font-size:20px;
}

.sub1 {
    font-family: 'ELAND_Choice_M';
    text-align: center;
    font-size:10px;
    margin-bottom: 2cm;
}

.sub2 {
    font-family: 'ELAND_Choice_M';
    text-align: center;
    font-size:17px;
}

.thought {
  display:flex;
  background-color:#fff;
  padding:20px;
  border-radius:30px;
  min-width:40px;
  max-width:220px;
  min-height:40px;
  margin:20px;
  position:relative;
  align-items:center;
  justify-content:center;
  text-align:center;
}
.thought:before,
.thought:after {
  content:"";
  background-color:#fff;
  border-radius:50%;
  display:block;
  position:absolute;
  z-index:-1;
}
.thought:before {
  width:44px;
  height:44px;
  top:-12px;
  left:28px;
  box-shadow:-50px 30px 0 -12px #fff;
}
.thought:after {
  bottom:-10px;
  right:26px;
  width:30px;
  height:30px;
  box-shadow:40px -34px 0 0 #fff,
             -28px -6px 0 -2px #fff,
             -24px 17px 0 -6px #fff,
             -5px 25px 0 -10px #fff;
  
}
.inputty{
    display:flex;
    padding:20px;
    border-radius:30px;
    min-width:40px;
    max-width:220px;
    min-height:40px;
    margin:20px;
    position:relative;
    align-items:center;
    justify-content:center;
    text-align:center;

}
.title{
    display:flex;
    padding:20px;
    border-radius:30px;
    min-width:40px;
    max-width:220px;
    min-height:40px;
    margin:20px;
    position:relative;
    
    text-align:center;

}

.title1{
    font-family: 'SBAggroB';
    font-size:40px;
}
.title2{
    font-family: 'Pretendard-Regular';
    
    font-size:20px;
}
</style>
<body>
    <div class="comment">
    <div class="title">
        <div class="title1">
        {{debate.title}}{{debate.text}}</div>
        
        
    </div>
    
    
    
        <div class="inputty"><form action="{%url 'community:comment_to_debate' debate.id %}" method="POST"></form></div>
            {% csrf_token %}
            <textarea name="debate_comment_text"></textarea>
            <button>추가</button>
        </form>
        
            {% for comment in debate_comments %}
            <div class="thought">
            <div class="sub2"><strong>{{comment.author}}</strong></div></b>
            <div class="ma"><br><br>{{comment.text}}<br><br></div>
            
            
            {% endfor %}
            
        </div>
        </div>
{%endblock%}

floo/community/templates/debate_main.html
{%extends 'base.html' %}
{%load static%}
{%block content%}

<head>
    <link rel="stylesheet" href='{% static "debate_main.css" %}' />
</head>
<div class="container-fluid">


    <div class="row row-cols-1 row-cols-md-4 g-4" id="main-container">
        {% for debate in debates.all %}

        
        <a href="{%url 'community:debate_detail' debate.id %}">
            <div class="col">
                <div class="card h-100" id="card">
                    
                    <div class="card-body">
                    <p id="rcorners1">{{debate.title}}</p>
                        
                    </div>
                    <div class="card-footer" style="border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;">
                        <small class="text-muted">
                            {{debate.date}}
                        </small>
                    </div>
                </div>
            </div>
        </a>

        
        {% endfor %}
    </div>

    
    

</section>

</div>

{%endblock%}

floo/community/templates/forbidden.html
404page

floo/community/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="banner" role="banner" style="background-color: #CCDBE2;">
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="banner-text text-center">
                <h1>FLOO</h1>
                <p style="font-weight:450">Yolo & Fire 당신은 어느쪽 입니까?</p>
                <a href="#download" class="btn btn-large" style="background-color: #8399a3;">Find out more</a>
            </div><!-- banner text -->
        </div>
    </div>
</section>



<body>


    <section id="download" class="section download">
        <div class="container">
            <div class="col-md-8 col-md-offset-2 text-center">
                <h3>About This Page</h3>
                <h4 style="margin-top: 80px;">욜로족과 파이어족을 위한 아래의 서비스를 제공합니다!</h4>
            </div>
        </div>
    </section>
    <section id="features" class="features section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-6 feature text-center">
                    <span class="icon icon-tools"></span>
                    <div class="feature-content">
                        <h5>영수증</h5>
                        <p>영수증을 업로드하여 당신의 욜로 또는 파이어 성향을 보여주세요! </p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 feature text-center">
                    <span class="icon icon-desktop"></span>
                    <div class="feature-content">
                        <h5>MBTI 테스트</h5>
                        <p>혹시 욜로족인지 파이어족인지 모르시나요! 그러면 저희가 준비한 테스트를 해보세요! </p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 feature text-center">
                    <span class="icon icon-genius"></span>
                    <div class="feature-content">
                        <h5>토론</h5>
                        <p>저희가 제공하는 재밌는 주제들을 가지고 욜로족과 파이어족이 서로 토론을해봐요 ! </p>
                    </div>
                </div>
    </section><!-- features -->


    <div class="container">
        <div class="col-md-8 col-md-offset-2 text-center">
            <h3>Developer</h3>
        </div>
    </div>

    <section id="teams" class="section teams">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="person">
                        <img src="{% static 'images/김수빈.png' %}" alt="" class="img-responsive">
                        <div class="person-content">
                            <h4>김수빈</h4>
                            <h5 class="role">국민대학교</h5>
                            <p>💻email : soobin851@gamil.com</p>
                        </div>
                    </div><!-- person -->
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="person">
                        <img src="{% static 'images/박주희.png' %}" alt="" class="img-responsive">
                        <div class="person-content">
                            <h4>박주희</h4>
                            <h5 class="role">단국대학교</h5>
                            <p>💻email : juliaee@naver.com</p>
                        </div>
                    </div><!-- person -->
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="person">
                        <img src="{% static 'images/서희찬.png' %}" alt="" class="img-responsive">
                        <div class="person-content">
                            <h4>서희찬</h4>
                            <h5 class="role">동국대학교</h5>
                            <p>💻email : gmlcks0513@naver.com </p>
                        </div>
                    </div><!-- person -->
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="person">
                        <img src="{% static 'images/최은윤.png' %}" alt="" class="img-responsive">
                        <div class="person-content">
                            <h4>최은윤</h4>
                            <h5 class="role">홍익대학교</h5>
                            <p>💻email : choiey073@naver.com</p>
                        </div>
                    </div><!-- person -->
                </div>
            </div>
        </div>
    </section><!-- teams -->

    <section id="testimonials" class="section testimonials no-padding">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="flexslider">
                    <ul class="slides">
                        <li>
                            <div class="col-md-6">
                                <div class="avatar">
                                    <img src="images/testimonial-1.jpg" alt="" class="img-responsive">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <blockquote>
                                    <p>"Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec sed
                                        odio dui. Aenean eu leo quam..."
                                    </p>
                                    <cite class="author">Susan Sims, Interaction Designer at XYZ</cite>
                                </blockquote>
                            </div>
                        </li>
                        <li>
                            <div class="col-md-6">
                                <div class="avatar">
                                    <img src="images/testimonial-2.jpg" alt="" class="img-responsive">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <blockquote>
                                    <p>"Cras mattis consectetur purus sit amet fermentum. Donec sed odio dui. Aenean
                                        lacinia bibendum nulla sed consectetur...."
                                    </p>
                                    <cite class="author">Susan Sims, Interaction Designer at XYZ</cite>
                                </blockquote>
                            </div>
                        </li>
                    </ul>
                </div><!-- flexslider -->
            </div>
        </div>
    </section>
    


</body>


{% endblock %}

floo/community/templates/main.html
community 의 메인페이지 입니다.

floo/community/templates/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800&amp;subset=korean" rel="stylesheet">
    <style>
        * {
            font-family: "Nanum Gothic", sans-serif;
            font-size: 23px;
        }

        #ti {
            font-family: "Nanum Gothic", sans-serif;
            font-size: 23px;
            color: rgb(255, 255, 255);
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <section id="ti" class="mx-auto mt-5 pt-5 pb-5 px-3" style="background-color: #CCDBE2;
        width:50%;
        text-align:center;
        border-radius: 10px;">
            마이페이지 입니다. {{user.get_username}}님 반갑습니다.

        </section>
    </div>

    <div class="container-fluid">
        <section class="mx-auto mt-5 pt-5 pb-5 px-3" style="background-color:white;
        width:80%;
        text-align:center;
        border-radius: 10px;">

            이름: {{user.get_username}}<br>
            NickName: {{user.nickname}}<br>
            profile: {{user.profile}}
        </section>
    </div>


    {% for bill in bills %}
    <div class="container-fluid">
        <section class="mx-auto mt-5 pt-5 pb-5 px-3" style="background-color:white;
        width:80%;
        text-align:center;
        border-radius: 10px;">

            <br>
            <H2>{{user.get_username}}님이 작성하신 글입니다</H2>
            <br>
            <h3>
                {{bill.image}}
            </h3>
            </a>
            <ul>
                <h3>
                    <li>제목: {{bill.title}}</li>
                    <li>작성일: {{bill.date}}</li>
                </h3>
            </ul>
        </section>
    </div>

</body>

</html>
{% endfor %}

{% endblock %}